### PR TITLE
Add more string types

### PR DESCRIPTION
**Pull request by viraptor**
Fixes issue #27

### CODE REVIEW

**Comment by kimgr** [comment]
Looks great! If there are no more string types, could you also remove the trailing TODO in the test file?

Many thanks!

**Comment by kimgr** [comment]
Actually, let me clean that up myself. Thanks for your patch!

**Comment by kimgr** [comment]
Oops, it looks like this PR only contained half of the change (only the codegen change + tests, not the parser changes.) Can you rebase and post a new PR? Thanks!

**Comment by viraptor** [comment]
That confused me too at first :) The parser already contained all the needed keywords and had them in the grammar.

**Comment by kimgr** [comment]
Oh, I see that now. Never mind me :-)

**Pull request merged**
